repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.4  # Replace with the latest version if available
    hooks:
      - id: ruff
        args: ["--config=.linting/ruff.toml", "."]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        additional_dependencies:
          - sqlalchemy
        args: ["--config-file=.linting/mypy.ini"]

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
        args: ["--config=.linting/.flake8"]
        additional_dependencies:
          - flake8-docstrings
          - darglint

  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.3.0  # check for latest version
    hooks:
      - id: pydocstyle
        args: ["--config=.linting/pydocstyle.ini"]