version: '3.8'

services:
    db:
        image: postgres:latest
        platform: linux
        container_name: postgres_local
        restart: always
        environment:
            POSTGRES_USER: laravel_user
            POSTGRES_PASSWORD: laravel_pass
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - appnet
volumes:
    pgdata:

networks:
    appnet:
