"""Add new column to clients.

Revision ID: 9b67c213912e
Create Date: 2025-06-03 15:15:09.308555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b67c213912e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'clients',
        sa.Column('portal_id', sa.Integer(), nullable=False),
        sa.Column('sales_id', sa.VARCHAR(), nullable=True),
        sa.PrimaryKeyConstraint('portal_id'),
        sa.UniqueConstraint('sales_id')
    )
    op.drop_index(op.f('client_map_portal_id_idx'), table_name='client_map')
    op.drop_index(op.f('client_map_sales_id_idx'), table_name='client_map')
    op.drop_table('client_map')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'client_map',
        sa.Column('sales_id', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('portal_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint('sales_id', name=op.f('client_map_pk')),
        sa.UniqueConstraint(
            'portal_id',
            name=op.f('client_map_unique'),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False
        )
    )
    op.create_index(
        op.f('client_map_sales_id_idx'),
        'client_map',
        ['sales_id'],
        unique=True
    )
    op.create_index(
        op.f('client_map_portal_id_idx'),
        'client_map',
        ['portal_id'],
        unique=True
    )
    op.drop_table('clients')
    # ### end Alembic commands ###
